<?php

namespace model;

class Question extends WPCustomPostType
{
    /**
     * @return array
     */
    public function getActiveS(): array
    {
        return self::Get(
            'question',
            'model\Question',
            [
                'key' => 'Question_Status',
                'value' => true,
                'compare' => '=',
                'type' => 'CHAR'
            ]
        );
    }

    /**
     * @return array
     */
    public function getInactiveS(): array
    {
        return self::Get(
            'question',
            'model\Question',
            [
                'key' => 'Question_Status',
                'value' => false,
                'compare' => '=',
                'type' => 'CHAR'
            ]
        );
    }

    public function getNumberUsed()
    {

    }

    public function getNumberAnswered()
    {

    }

    public function getType()
    {
        return $this->getPostMeta('Question_type');
    }

    public function getActivation()
    {
        return parent::getActivation(); // TODO: Change the autogenerated stub
    }

    public function updateActivation($value): bool
    {
        return parent::updateActivation($value);
    }

    /**
     * @return bool
     */
    public static function IsThisQuestion(): bool
    {
        return WPInstrument::CheckCurrentCustomPostTypeInArray(self::GetServiceCustomPostTypes());

    }

    /**
     * @return string[]
     */
    public static function GetServiceCustomPostTypes(): array
    {
        return ['question'];
    }
}