<?php

namespace model;

class Solution extends WPCustomPostType
{

    /**
     * @param $ID
     */
    public function __construct($ID)
    {
        parent::__construct($ID);
    }

    /**
     * @return array|int|string
     */
    public function getActivation()
    {
        return parent::getActivation(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $value
     * @return bool
     */
    public function updateActivation($value): bool
    {
        return parent::updateActivation($value); // TODO: Change the autogenerated stub
    }

    /**
     * @return bool
     */
    public static function IsThisSolution(): bool
    {
        return WPInstrument::CheckCurrentCustomPostTypeInArray(self::GetServiceCustomPostTypes());

    }

    /**
     * @return string[]
     */
    public static function GetServiceCustomPostTypes(): array
    {
        return ['solution'];
    }

    /**
     * @return array model\Solution
     */
    public static function GetAllSolutionList(): array
    {
        return parent::GetAll('solution', 'model\Solution');
    }

    /**
     * @return array
     */
    public static function GetActiveS(): array
    {
        return self::Get(
            'solution',
            'model\Solution',
            [
                array(
                    'key' => 'Activation_Status',
                    'value' => '1',
                    'compare' => '='
                )
            ]
        );
    }

    /**
     * @return array
     */
    public static function GetInactiveS(): array
    {
        return self::Get(
            'solution',
            'model\Solution',
            [
                array(
                    'key' => 'Activation_Status',
                    'value' => '2',
                    'compare' => '='
                )
            ]
        );
    }
}